# Generated by Django 6.0.5 on 2026-06-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
