# Generated by Django 6.0.5 on 2026-06-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
