# Generated by Django 6.0.5 on 2026-06-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nin_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
