# Generated by Django 6.0.5 on 2026-07-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_pendingapplicationnotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingapplicationnotification',
            new_name='application_scheme__7ca57e_idx',
            old_name='applications_scheme_sent_idx',
        ),
    ]
