# Generated by Django 6.0.5 on 2026-06-08 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(blank=True, default='', max_length=50)),
                ('lastname', models.CharField(blank=True, default='', max_length=50)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('active_award', models.CharField(blank=True, max_length=300)),
                ('nin_hash', models.CharField(blank=True, default='', max_length=20)),
                ('lga', models.CharField(blank=True, max_length=80)),
                ('passport', models.FileField(blank=True, null=True, upload_to='')),
                ('ward', models.CharField(blank=True, max_length=40)),
                ('date_of_birth', models.DateField(null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('course_of_study', models.CharField(max_length=100)),
                ('current_level', models.CharField(max_length=100)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.student')),
            ],
        ),
    ]
