# Generated by Django 6.0.5 on 2026-06-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nin_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
