# Generated by Django 6.0.5 on 2026-07-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_nin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
