# Generated by Django 6.0.5 on 2026-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
