# Generated by Django 6.0.5 on 2026-07-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=10),
        ),
    ]
