# Generated by Django 6.0.5 on 2026-07-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passports',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
