# Generated by Django 6.0.5 on 2026-07-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_passports_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passports',
        ),
    ]
