# Generated by Django 6.0.5 on 2026-06-08 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='SchemeProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('provider_type', models.CharField(choices=[('lga', 'LGA Council'), ('state', 'State Government'), ('corporate', 'Corporate / CSR'), ('ngo', 'NGO / Foundation'), ('federal', 'Federal Government')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('award_type', models.CharField(choices=[('scholarship', 'Scholarship (Academic)'), ('empowerment', 'Empowerment / Vocational Training'), ('grant', 'Grant')], default='scholarship', max_length=20)),
                ('description', models.TextField()),
                ('academic_year', models.CharField(max_length=9)),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_slots', models.IntegerField()),
                ('remaining_slots', models.IntegerField()),
                ('stacking_policy', models.CharField(choices=[('exclusive', 'Exclusive — no other active awards allowed'), ('major_only', 'Cannot stack with other major awards'), ('open', 'Open — can stack with any award')], default='major_only', max_length=20)),
                ('eligibility_criteria', models.JSONField(default=dict)),
                ('application_open_date', models.DateField()),
                ('application_close_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_name', models.CharField(blank=True, default='', editable=False, max_length=63)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes', to='schemes.cycle')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='schemes.schemeprovider')),
            ],
        ),
    ]
